# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: DotNet2Test
    pool:
      name: BegonaDev
    steps:
      - task: UseDotNet@2
        displayName: "Use .Net Core 2.1.700"
        inputs:
          version: 2.1.700

      - task: Cache@2
        inputs:
          key: 'nuget | "$(Agent.OS)" | packages.lock.json'
          restoreKeys: |
            nuget | "$(Agent.OS)"
            nuget
          path: $(NUGET_PACKAGES)
        displayName: Cache NuGet packages

      - task: DotNetCoreCLI@2
        displayName: "restore packages"
        inputs:
          command: restore
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: "build"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "**/demo-dot-net-2.csproj"
        
      - task: PublishBuildArtifacts@1
        displayName: "publish artifacts"
        inputs:
          ArtifactName: Demo 2
