# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: DotNet2Test
    pool:
      vmImage: 'macOS-latest'
      # name: BegonaDev
    steps:
      - script: echo $(Build.Repository.Name)
      - task: UseDotNet@2
        displayName: "Use .Net Core 2.1.700"
        inputs:
          version: 2.1.700

      - task: Cache@2
        displayName: Cache NuGet packages
        inputs:
          key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/packages.lock.json'
          restoreKeys: |
            nuget | "$(Agent.OS)"
            nuget
          path: $(NUGET_PACKAGES)
          cacheHitVar: $(cacheHit)

      - task: DotNetCoreCLI@2
        condition: eq(variables['cacheHit'], 'true')
        displayName: "Restore Packages"
        inputs:
          command: restore
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: "build"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "**/*.csproj"
          feedsToUse: config
          nugetConfigPath: '$(Build.Repository.Name)/NuGet.Config'
        
      - task: PublishBuildArtifacts@1
        displayName: "publish artifacts"
        inputs:
          ArtifactName: Dot Net Demo Artifacts
